# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tmon.proto\x12\nmonitoring\"\x06\n\x04Void\"d\n\x05Stats\x12\x1d\n\x03mem\x18\x01 \x01(\x0b\x32\x10.monitoring.Stat\x12\x1d\n\x03\x63pu\x18\x02 \x01(\x0b\x32\x10.monitoring.Stat\x12\x1d\n\x03net\x18\x03 \x01(\x0b\x32\x10.monitoring.Stat\"K\n\x04Stat\x12\"\n\x04host\x18\x01 \x01(\x0b\x32\x14.monitoring.HostStat\x12\x1f\n\x03vms\x18\x02 \x03(\x0b\x32\x12.monitoring.VmStat\"\x88\x01\n\x08HostStat\x12\x36\n\thistogram\x18\x01 \x03(\x0b\x32#.monitoring.HostStat.HistogramEntry\x12\x12\n\ntimeseries\x18\x02 \x03(\x02\x1a\x30\n\x0eHistogramEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x93\x01\n\x06VmStat\x12\r\n\x05vm_id\x18\x01 \x01(\t\x12\x34\n\thistogram\x18\x02 \x03(\x0b\x32!.monitoring.VmStat.HistogramEntry\x12\x12\n\ntimeseries\x18\x03 \x03(\x02\x1a\x30\n\x0eHistogramEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32?\n\nMonitoring\x12\x31\n\x08GetStats\x12\x10.monitoring.Void\x1a\x11.monitoring.Stats\"\x00\x42#\n\x14io.grpc.examples.MonB\x03MonP\x01\xa2\x02\x03Monb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\024io.grpc.examples.MonB\003MonP\001\242\002\003Mon'
  _HOSTSTAT_HISTOGRAMENTRY._options = None
  _HOSTSTAT_HISTOGRAMENTRY._serialized_options = b'8\001'
  _VMSTAT_HISTOGRAMENTRY._options = None
  _VMSTAT_HISTOGRAMENTRY._serialized_options = b'8\001'
  _VOID._serialized_start=25
  _VOID._serialized_end=31
  _STATS._serialized_start=33
  _STATS._serialized_end=133
  _STAT._serialized_start=135
  _STAT._serialized_end=210
  _HOSTSTAT._serialized_start=213
  _HOSTSTAT._serialized_end=349
  _HOSTSTAT_HISTOGRAMENTRY._serialized_start=301
  _HOSTSTAT_HISTOGRAMENTRY._serialized_end=349
  _VMSTAT._serialized_start=352
  _VMSTAT._serialized_end=499
  _VMSTAT_HISTOGRAMENTRY._serialized_start=301
  _VMSTAT_HISTOGRAMENTRY._serialized_end=349
  _MONITORING._serialized_start=501
  _MONITORING._serialized_end=564
# @@protoc_insertion_point(module_scope)
